### ISSUE TITLE
fs.walk raise fs.errors.ResourceNotFound

### ISSUE THREAD

**Issue by hevy-CC4477** [PyFilesystem/s3fs#5]
Hi,

I tried to use this new version of s3fs and I don't succeed to use walk.

```
% aws s3 ls --recursive s3://hevytest
2017-09-25 15:29:38          0 tmp/tmp
% python
Python 2.7.13 (default, Jul 18 2017, 09:17:00)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fs import open_fs
>>> with open_fs('s3://hevytest') as fs:
...     for path in fs.walk():
...             print path
...
(u'/', [<dir 'tmp'>], [])
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/hevy/env/lib/python2.7/site-packages/fs/walk.py", line 293, in _walk_breadth
    for info in self._scan(fs, dir_path, namespaces=namespaces):
  File "/Users/hevy/env/lib/python2.7/site-packages/fs_s3fs/_s3fs.py", line 621, in scandir
    info = self.getinfo(path)
  File "/Users/hevy/env/lib/python2.7/site-packages/fs_s3fs/_s3fs.py", line 418, in getinfo
    obj = self._get_object(path, _key)
  File "/Users/hevy/env/lib/python2.7/site-packages/fs_s3fs/_s3fs.py", line 325, in _get_object
    return obj
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/hevy/env/lib/python2.7/site-packages/fs_s3fs/_s3fs.py", line 180, in s3errors
    raise errors.ResourceNotFound(path)
fs.errors.ResourceNotFound: resource '/tmp' not found
```

Why fs.errors.ResourceNotFound is raised ? Did I do something wrong ?

My environment:
```
% pip freeze
appdirs==1.4.3
boto3==1.4.7
botocore==1.7.16
docutils==0.14
enum34==1.1.6
fs==2.0.10
fs-s3fs==0.1.3
futures==3.1.1
jmespath==0.9.3
python-dateutil==2.6.1
pytz==2017.2
s3transfer==0.1.11
six==1.10.0
```

**Comment by willmcgugan** [comment]
That's probably because there is no empty `tmp/` object which would indicate a directory. If you create it, you might find it works. If you use S3FS to create files, it will create directory objects for you.

It might be possible to handle these implied directories. I'll look in to it.

**Comment by hevy-CC4477** [comment]
empty `tmp/` ? I don't understand, you can't have an empty `tmp/`.

**Comment by willmcgugan** [comment]
S3 doesn't support true directories, so S3FS (and S3 console) will create an object with 0 bytes for each directory. So in your example, there would be two objects; one called `tmp/` and one called `tmp/tmp`.

How did you create that file?

**Comment by hevy-CC4477** [comment]
I created the file using the aws cli:
`touch tmp && aws s3 mv tmp s3://hevytest/tmp/tmp`

As you say, S3 does not support directories. It's just keys. I can understand that for other filesystem you use them. Do you think you could implied them ?

**Comment by willmcgugan** [comment]
Yeah, it's probably possible. I'll look in to it.

**Comment by willmcgugan** [comment]
Can't see an efficient solution for this. Best I can do is [document the behaviour](http://fs-s3fs.readthedocs.io/en/latest/#limitations).

**Comment by mivade** [comment]
Is there any interest in revisiting this sort of issue? I would really like to use PyFilesystem but the S3 limitations prevent me from doing so. In my case I don't always have control over what's in S3 which means there may be missing empty objects. If I had write access then I could create them, but I don't always have that, either.

At the very least, would it be possible to be more explicit in the documentation about when missing an empty object is problematic? Right now the documentation just says, "You *may* run in to problems," without saying anything about which sorts of operations are likely to encounter errors.

For what it's worth, I was trying to use this a while back and this limitation forced me to refactor a lot of code since the workaround (create the empty objects) is not always possible.

**Comment by willmcgugan** [comment]
I would love to be able to offer you an alternative, but to make it work transparently without objects to indicate directories would be horribly inefficient. It would require listing all the buckets and deducing the directory structure. A process which would make this class next to useless for real-word tasks.

If you have a practical solution for this or want to update the docs, feel free to raise a PR.

**Comment by mivade** [comment]
Thanks for the quick reply! I actually can't remember precisely which operations were causing issues for me but I don't think it was `walk` (so apologies if resurrecting the discussion here is inappropriate). Most likely it was something like just a simple listing of a directory rather than walking.

I'm not too familiar with the internals here but if I have time (unfortunately not too likely for the foreseeable future) I'll look and see if I can at least identify where problems are most likely to be encountered.

**Comment by mivade** [comment]
OK I lied and spent a little time looking at the code. It turns out that the issue I had before was in opening a file and that is a result of this line: https://github.com/PyFilesystem/s3fs/blob/7f95af69e904e58b068ac4f6b39c2da488d5d918/fs_s3fs/_s3fs.py#L438. I can work around this by constructing a `S3FS` object directly with `strict=False`. To me this warrants some extra discussion in the docs so I'll open a PR.
